version: "3.8"

services:
  backend:
    build: ./backend
    container_name: christapp-backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build: ./frontend
    container_name: christapp-client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.local.docker
    restart: always

  bibleapi:
    build: ./BibleAPI
    container_name: christapp-bibleapi
    ports:
      - "3002:3002"
    restart: always
